### ISSUE TITLE
[Implement rule] License file exists and has content

### ISSUE THREAD

**Issue by fhocutt** [OpenNewsLabs/open-project-linter#11]

**Comment by brainwane** [comment]
The file might be called `LICENSE` or  `COPYING`.

**Comment by brainwane** [comment]
Please also accommodate `LICENSE.txt`, e.g., as https://github.com/EFForg/https-everywhere/ uses.

**Comment by brainwane** [comment]
And `LICENSE.md`, as https://github.com/swcarpentry/git-novice/ uses.

**Comment by brainwane** [comment]
And `COPYING.txt`, as in https://gitlab.com/mailman/hyperkitty/tree/master .

**Comment by brainwane** [comment]
And `README.rst`, as in https://phabricator.wikimedia.org/diffusion/PWBC/browse/master/ .

**Comment by fhocutt** [comment]
@brainwane: I'll implement a check for multiple possible filenames for a single file--this should be a pretty simple change. Right now, the tool checks for the presence of a given string (`"LICENSE"`, for instance) as a substring of any of the filenames present in the given directory, so `LICENSE.md` and `LICENSE.txt` will both be detected. Is this reasonable behavior?

**Comment by brainwane** [comment]
@fhocutt Thanks -- that is reasonable behavior in my opinion. :)
