### ISSUE TITLE
[Implement rule] Check for development branches

### ISSUE THREAD

**Issue by fhocutt** [OpenNewsLabs/open-project-linter#15]
If the project to be checked is using git, there should be commits on multiple branches.

**Comment by brainwane** [comment]
Checking for a branch named "feature" would also be good.

**Comment by fhocutt** [comment]
@brainwane: In addition to the check for "develop", or should it pass the check if either "develop" or "feature" branches are present?

**Comment by brainwane** [comment]
@fhocutt Yes - if either a `develop` or a `feature` branch is present, let's have the check pass.

**Comment by fhocutt** [comment]
Specific branch names are configurable in `rules.yml`.
