### ISSUE TITLE
Publish project on PyPI.

### ISSUE THREAD

**Issue by fhocutt** [OpenNewsLabs/open-project-linter#2]

**Comment by brainwane** [comment]
Frances will be referring to https://packaging.python.org/distributing/#packaging-your-project .

**Comment by fhocutt** [comment]
Successfully packaged and uploaded the current version to testpypi: https://testpypi.python.org/pypi/open-project-linter/0.1dev

**Comment by fhocutt** [comment]
https://pypi.python.org/pypi/open-project-linter
