### ISSUE TITLE
Write a first implementation of the command-line interface

### ISSUE THREAD

**Issue by fhocutt** [OpenNewsLabs/open-project-linter#21]
*Acceptance criteria*
A user should be able to run the app from the command line and:
- [x] Indicate whether the project to be checked is local or hosted on Github (First, support only local repositories of unversioned code, #5)
- [x] Indicate that they would like to check the project using one or more configurable rules
- [x] Available rules will be checking for presence of one or more files (LICENSE, README, etc.)
- [x] Get help on running the app
- [x] Have the app check the project, according to the rules
- [x] Read the results as printed to stdout

**Comment by fhocutt** [comment]
See also: #4, #5, #3.

**Comment by fhocutt** [comment]
@brainwane: ping! Also, some questions:

* Is it worth distinguishing between "file does not exist" and "file exists but does not have content"?
* Any thoughts on how to handle interface strings? Options range from "hard-code everything" (easiest at the moment of coding) to "stick them in a config file somewhere" to "find a handy localization system".
* Any thoughts on result handling? Could do it with print() as the program runs (harder to test, probably, though if you're testing the inputs it could be worse), could pass around a result object and print it/save it when the program's finished.

**Comment by brainwane** [comment]
> Is it worth distinguishing between "file does not exist" and "file exists but does not have content"?

Yes!

>    Any thoughts on how to handle interface strings? Options range from "hard-code everything" (easiest at the moment of coding) to "stick them in a config file somewhere" to "find a handy localization system".

I believe you put them in a config file, which is good enough for now, I think.

>    Any thoughts on result handling? Could do it with print() as the program runs (harder to test, probably, though if you're testing the inputs it could be worse), could pass around a result object and print it/save it when the program's finished.

I believe you decided to put them in an object for easier testing, which is good. :)

**Comment by fhocutt** [comment]
The strings to search for (filenames like LICENSE) are in a config file, but the output (e.g. `! $filename is not found in $directory` is currently hard-coded.

**Comment by brainwane** [comment]
Ah! Thanks. That seems fine to me for now since "Ensure that interface messages are stored together and are easy to find and modify" is in the roadmap.
