### ISSUE TITLE
add more context to README.md

### ISSUE THREAD

**Issue by brainwane** [OpenNewsLabs/open-project-linter#23]
I am pretty happy with the existing context in the README but I just wrote this for the announcement and figured it might also be useful to consider putting someplace:

> This linter is designed and written by Frances Hocutt https://franceshocutt.com/cv/ via Changeset Consulting http://changeset.nyc/ , a project management and maintainership consultancy focusing on open source. Sumana Harihareswara of Changeset Consulting attended the document sprint and initially suggested offering a tool alongside the playbook to automate the checklist as much as possible. We look forward to seeing the community add new linter rules to help new maintainers.

**Comment by ryanpitts** [comment]
updated in https://github.com/OpenNewsLabs/open-project-linter/commit/67190a6b6c0e414a27e79ddf85bf36a28adeaf89
