### ISSUE TITLE
Issue on install (missing README.md?)

### ISSUE THREAD

**Issue by zzolo** [OpenNewsLabs/open-project-linter#26]
I get the following issue doing the install.  It looks like its looking for the README but can't find it?

```
zzolo:~ ⚡  pip install --pre open-project-linter
Collecting open-project-linter
  Downloading open-project-linter-0.3dev.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vw/83ycjjfs6bz0ht0vvcspf_vr0000gn/T/pip-build-FSDUA1/open-project-linter/setup.py", line 14, in <module>
        with(open(path.join(here, 'README.md'), encoding='utf-8')) as f:
      File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/vw/83ycjjfs6bz0ht0vvcspf_vr0000gn/T/pip-build-FSDUA1/open-project-linter/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vw/83ycjjfs6bz0ht0vvcspf_vr0000gn/T/pip-build-FSDUA1/open-project-linter/
```

**Comment by ryanpitts** [comment]
Hmm, interesting. I can replicate this with a Python 2.7 virtualenv, same IOError:

> IOError: [Errno 2] No such file or directory: '/private/var/folders/3d/7yj2dyq96d74m8nbtm_1f0580000gn/T/pip-build-3zkj2d/open-project-linter/README.md'

This doesn't happen with Python3 (although there's a [different pip install](https://github.com/OpenNewsLabs/open-project-linter/issues/24) issue there).

**Comment by fhocutt** [comment]
This is a 2-to-3 compatibility issue. The problem is that 2.7 doesn't expect to be given an encoding for open() (since it outputs a bytestring), so it chokes.

Python 2 is not currently supported, but I'll make a stronger note in the README and put 2-to-3 compatibility on the roadmap.

**Comment by zzolo** [comment]
It's also my fault for not seeing it (basically) right in front of me.

**Comment by brainwane** [comment]
@zzolo Hey, if you didn't see it, other users wouldn't see it either! We're grateful for an opportunity to reduce friction. :)
