### ISSUE TITLE
Design the command-line UI

### ISSUE THREAD

**Issue by fhocutt** [OpenNewsLabs/open-project-linter#4]
* Should have useful help text, probably pointing to the checklist
* Needs: to have an idea what capabilities and configurations the app has

**Comment by brainwane** [comment]
> Needs: to have an idea what capabilities and configurations the app has

You mean which capabilities and configurations the linter has, or the code being linted?

**Comment by fhocutt** [comment]
For command-line help, run `$ openlinter --help` or `$ python3 path/to/openlinter.py --help`.
